# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "blog example"
email: "foo@example.com"
description: >- # this means to ignore newlines until "baseurl:"
  Description
logo: "/assets/images/dummy.png"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.example.com" # the base hostname & protocol for your site, e.g. http://example.com
paginate: 10 # The number of posts to show per page on your homepage

name: 'Example User'
bio: >
  BIO can use <b>HTML</b>.
author_image: "/assets/images/dummy.png"
twitter_username: "search"
github_username: "explore"

# Google Analytics
analytics_id: ""

# Google AdSense
ad_client: ""

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true

plugins:
- jekyll-paginate
- jekyll-last-modified-at

permalink: /:categories/:year-:month-:day-:title.html
strict_front_matter: true

# jekyll-tagging
tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty

jekyll-minifier:
  exclude: '*.xml'
  exclude: '_*'

include:
- "_headers"
- "_redirects"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
- Gemfile
- Gemfile.lock
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- netlify.toml
